/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moonsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BroadCastRawTransactionAPIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BroadCastRawTransactionAPIResponse{}

// BroadCastRawTransactionAPIResponse struct for BroadCastRawTransactionAPIResponse
type BroadCastRawTransactionAPIResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	Body *InputBody `json:"body,omitempty"`
	Address *string `json:"address,omitempty"`
	Data *BroadCastRawTransactionResponse `json:"data,omitempty"`
}

type _BroadCastRawTransactionAPIResponse BroadCastRawTransactionAPIResponse

// NewBroadCastRawTransactionAPIResponse instantiates a new BroadCastRawTransactionAPIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBroadCastRawTransactionAPIResponse(success bool, message string) *BroadCastRawTransactionAPIResponse {
	this := BroadCastRawTransactionAPIResponse{}
	this.Success = success
	this.Message = message
	return &this
}

// NewBroadCastRawTransactionAPIResponseWithDefaults instantiates a new BroadCastRawTransactionAPIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBroadCastRawTransactionAPIResponseWithDefaults() *BroadCastRawTransactionAPIResponse {
	this := BroadCastRawTransactionAPIResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *BroadCastRawTransactionAPIResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *BroadCastRawTransactionAPIResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *BroadCastRawTransactionAPIResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *BroadCastRawTransactionAPIResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BroadCastRawTransactionAPIResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BroadCastRawTransactionAPIResponse) SetMessage(v string) {
	o.Message = v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *BroadCastRawTransactionAPIResponse) GetBody() InputBody {
	if o == nil || IsNil(o.Body) {
		var ret InputBody
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadCastRawTransactionAPIResponse) GetBodyOk() (*InputBody, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *BroadCastRawTransactionAPIResponse) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given InputBody and assigns it to the Body field.
func (o *BroadCastRawTransactionAPIResponse) SetBody(v InputBody) {
	o.Body = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *BroadCastRawTransactionAPIResponse) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadCastRawTransactionAPIResponse) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *BroadCastRawTransactionAPIResponse) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *BroadCastRawTransactionAPIResponse) SetAddress(v string) {
	o.Address = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BroadCastRawTransactionAPIResponse) GetData() BroadCastRawTransactionResponse {
	if o == nil || IsNil(o.Data) {
		var ret BroadCastRawTransactionResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadCastRawTransactionAPIResponse) GetDataOk() (*BroadCastRawTransactionResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BroadCastRawTransactionAPIResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given BroadCastRawTransactionResponse and assigns it to the Data field.
func (o *BroadCastRawTransactionAPIResponse) SetData(v BroadCastRawTransactionResponse) {
	o.Data = &v
}

func (o BroadCastRawTransactionAPIResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BroadCastRawTransactionAPIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *BroadCastRawTransactionAPIResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBroadCastRawTransactionAPIResponse := _BroadCastRawTransactionAPIResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBroadCastRawTransactionAPIResponse)

	if err != nil {
		return err
	}

	*o = BroadCastRawTransactionAPIResponse(varBroadCastRawTransactionAPIResponse)

	return err
}

type NullableBroadCastRawTransactionAPIResponse struct {
	value *BroadCastRawTransactionAPIResponse
	isSet bool
}

func (v NullableBroadCastRawTransactionAPIResponse) Get() *BroadCastRawTransactionAPIResponse {
	return v.value
}

func (v *NullableBroadCastRawTransactionAPIResponse) Set(val *BroadCastRawTransactionAPIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBroadCastRawTransactionAPIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBroadCastRawTransactionAPIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBroadCastRawTransactionAPIResponse(val *BroadCastRawTransactionAPIResponse) *NullableBroadCastRawTransactionAPIResponse {
	return &NullableBroadCastRawTransactionAPIResponse{value: val, isSet: true}
}

func (v NullableBroadCastRawTransactionAPIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBroadCastRawTransactionAPIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


