/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moonsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BroadCastRawTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BroadCastRawTransactionResponse{}

// BroadCastRawTransactionResponse struct for BroadCastRawTransactionResponse
type BroadCastRawTransactionResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	Data string `json:"data"`
}

type _BroadCastRawTransactionResponse BroadCastRawTransactionResponse

// NewBroadCastRawTransactionResponse instantiates a new BroadCastRawTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBroadCastRawTransactionResponse(success bool, message string, data string) *BroadCastRawTransactionResponse {
	this := BroadCastRawTransactionResponse{}
	this.Success = success
	this.Message = message
	this.Data = data
	return &this
}

// NewBroadCastRawTransactionResponseWithDefaults instantiates a new BroadCastRawTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBroadCastRawTransactionResponseWithDefaults() *BroadCastRawTransactionResponse {
	this := BroadCastRawTransactionResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *BroadCastRawTransactionResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *BroadCastRawTransactionResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *BroadCastRawTransactionResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *BroadCastRawTransactionResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BroadCastRawTransactionResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BroadCastRawTransactionResponse) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *BroadCastRawTransactionResponse) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BroadCastRawTransactionResponse) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BroadCastRawTransactionResponse) SetData(v string) {
	o.Data = v
}

func (o BroadCastRawTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BroadCastRawTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BroadCastRawTransactionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBroadCastRawTransactionResponse := _BroadCastRawTransactionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBroadCastRawTransactionResponse)

	if err != nil {
		return err
	}

	*o = BroadCastRawTransactionResponse(varBroadCastRawTransactionResponse)

	return err
}

type NullableBroadCastRawTransactionResponse struct {
	value *BroadCastRawTransactionResponse
	isSet bool
}

func (v NullableBroadCastRawTransactionResponse) Get() *BroadCastRawTransactionResponse {
	return v.value
}

func (v *NullableBroadCastRawTransactionResponse) Set(val *BroadCastRawTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBroadCastRawTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBroadCastRawTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBroadCastRawTransactionResponse(val *BroadCastRawTransactionResponse) *NullableBroadCastRawTransactionResponse {
	return &NullableBroadCastRawTransactionResponse{value: val, isSet: true}
}

func (v NullableBroadCastRawTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBroadCastRawTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


