/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moonsdk

import (
	"encoding/json"
)

// checks if the TronTransactionOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TronTransactionOutput{}

// TronTransactionOutput struct for TronTransactionOutput
type TronTransactionOutput struct {
	SignedTx *string `json:"signedTx,omitempty"`
	TransactionHash *string `json:"transaction_hash,omitempty"`
}

// NewTronTransactionOutput instantiates a new TronTransactionOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTronTransactionOutput() *TronTransactionOutput {
	this := TronTransactionOutput{}
	return &this
}

// NewTronTransactionOutputWithDefaults instantiates a new TronTransactionOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTronTransactionOutputWithDefaults() *TronTransactionOutput {
	this := TronTransactionOutput{}
	return &this
}

// GetSignedTx returns the SignedTx field value if set, zero value otherwise.
func (o *TronTransactionOutput) GetSignedTx() string {
	if o == nil || IsNil(o.SignedTx) {
		var ret string
		return ret
	}
	return *o.SignedTx
}

// GetSignedTxOk returns a tuple with the SignedTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TronTransactionOutput) GetSignedTxOk() (*string, bool) {
	if o == nil || IsNil(o.SignedTx) {
		return nil, false
	}
	return o.SignedTx, true
}

// HasSignedTx returns a boolean if a field has been set.
func (o *TronTransactionOutput) HasSignedTx() bool {
	if o != nil && !IsNil(o.SignedTx) {
		return true
	}

	return false
}

// SetSignedTx gets a reference to the given string and assigns it to the SignedTx field.
func (o *TronTransactionOutput) SetSignedTx(v string) {
	o.SignedTx = &v
}

// GetTransactionHash returns the TransactionHash field value if set, zero value otherwise.
func (o *TronTransactionOutput) GetTransactionHash() string {
	if o == nil || IsNil(o.TransactionHash) {
		var ret string
		return ret
	}
	return *o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TronTransactionOutput) GetTransactionHashOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionHash) {
		return nil, false
	}
	return o.TransactionHash, true
}

// HasTransactionHash returns a boolean if a field has been set.
func (o *TronTransactionOutput) HasTransactionHash() bool {
	if o != nil && !IsNil(o.TransactionHash) {
		return true
	}

	return false
}

// SetTransactionHash gets a reference to the given string and assigns it to the TransactionHash field.
func (o *TronTransactionOutput) SetTransactionHash(v string) {
	o.TransactionHash = &v
}

func (o TronTransactionOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TronTransactionOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SignedTx) {
		toSerialize["signedTx"] = o.SignedTx
	}
	if !IsNil(o.TransactionHash) {
		toSerialize["transaction_hash"] = o.TransactionHash
	}
	return toSerialize, nil
}

type NullableTronTransactionOutput struct {
	value *TronTransactionOutput
	isSet bool
}

func (v NullableTronTransactionOutput) Get() *TronTransactionOutput {
	return v.value
}

func (v *NullableTronTransactionOutput) Set(val *TronTransactionOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableTronTransactionOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableTronTransactionOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTronTransactionOutput(val *TronTransactionOutput) *NullableTronTransactionOutput {
	return &NullableTronTransactionOutput{value: val, isSet: true}
}

func (v NullableTronTransactionOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTronTransactionOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


