/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the Transaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transaction{}

// Transaction struct for Transaction
type Transaction struct {
	MoonScanUrl *string `json:"moon_scan_url,omitempty"`
	TransactionHash string `json:"transaction_hash"`
	SignedTransaction string `json:"signed_transaction"`
	SignedMessage *string `json:"signed_message,omitempty"`
	RawTransaction *string `json:"raw_transaction,omitempty"`
	Signature *string `json:"signature,omitempty"`
	Transaction *map[string]Tx `json:"transaction,omitempty"`
	UserOps []TransactionRequest `json:"userOps,omitempty"`
	UseropTransaction *string `json:"userop_transaction,omitempty"`
}

type _Transaction Transaction

// NewTransaction instantiates a new Transaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransaction(transactionHash string, signedTransaction string) *Transaction {
	this := Transaction{}
	this.TransactionHash = transactionHash
	this.SignedTransaction = signedTransaction
	return &this
}

// NewTransactionWithDefaults instantiates a new Transaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionWithDefaults() *Transaction {
	this := Transaction{}
	return &this
}

// GetMoonScanUrl returns the MoonScanUrl field value if set, zero value otherwise.
func (o *Transaction) GetMoonScanUrl() string {
	if o == nil || IsNil(o.MoonScanUrl) {
		var ret string
		return ret
	}
	return *o.MoonScanUrl
}

// GetMoonScanUrlOk returns a tuple with the MoonScanUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetMoonScanUrlOk() (*string, bool) {
	if o == nil || IsNil(o.MoonScanUrl) {
		return nil, false
	}
	return o.MoonScanUrl, true
}

// HasMoonScanUrl returns a boolean if a field has been set.
func (o *Transaction) HasMoonScanUrl() bool {
	if o != nil && !IsNil(o.MoonScanUrl) {
		return true
	}

	return false
}

// SetMoonScanUrl gets a reference to the given string and assigns it to the MoonScanUrl field.
func (o *Transaction) SetMoonScanUrl(v string) {
	o.MoonScanUrl = &v
}

// GetTransactionHash returns the TransactionHash field value
func (o *Transaction) GetTransactionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetTransactionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionHash, true
}

// SetTransactionHash sets field value
func (o *Transaction) SetTransactionHash(v string) {
	o.TransactionHash = v
}

// GetSignedTransaction returns the SignedTransaction field value
func (o *Transaction) GetSignedTransaction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignedTransaction
}

// GetSignedTransactionOk returns a tuple with the SignedTransaction field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetSignedTransactionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignedTransaction, true
}

// SetSignedTransaction sets field value
func (o *Transaction) SetSignedTransaction(v string) {
	o.SignedTransaction = v
}

// GetSignedMessage returns the SignedMessage field value if set, zero value otherwise.
func (o *Transaction) GetSignedMessage() string {
	if o == nil || IsNil(o.SignedMessage) {
		var ret string
		return ret
	}
	return *o.SignedMessage
}

// GetSignedMessageOk returns a tuple with the SignedMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetSignedMessageOk() (*string, bool) {
	if o == nil || IsNil(o.SignedMessage) {
		return nil, false
	}
	return o.SignedMessage, true
}

// HasSignedMessage returns a boolean if a field has been set.
func (o *Transaction) HasSignedMessage() bool {
	if o != nil && !IsNil(o.SignedMessage) {
		return true
	}

	return false
}

// SetSignedMessage gets a reference to the given string and assigns it to the SignedMessage field.
func (o *Transaction) SetSignedMessage(v string) {
	o.SignedMessage = &v
}

// GetRawTransaction returns the RawTransaction field value if set, zero value otherwise.
func (o *Transaction) GetRawTransaction() string {
	if o == nil || IsNil(o.RawTransaction) {
		var ret string
		return ret
	}
	return *o.RawTransaction
}

// GetRawTransactionOk returns a tuple with the RawTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetRawTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.RawTransaction) {
		return nil, false
	}
	return o.RawTransaction, true
}

// HasRawTransaction returns a boolean if a field has been set.
func (o *Transaction) HasRawTransaction() bool {
	if o != nil && !IsNil(o.RawTransaction) {
		return true
	}

	return false
}

// SetRawTransaction gets a reference to the given string and assigns it to the RawTransaction field.
func (o *Transaction) SetRawTransaction(v string) {
	o.RawTransaction = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *Transaction) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *Transaction) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *Transaction) SetSignature(v string) {
	o.Signature = &v
}

// GetTransaction returns the Transaction field value if set, zero value otherwise.
func (o *Transaction) GetTransaction() map[string]Tx {
	if o == nil || IsNil(o.Transaction) {
		var ret map[string]Tx
		return ret
	}
	return *o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetTransactionOk() (*map[string]Tx, bool) {
	if o == nil || IsNil(o.Transaction) {
		return nil, false
	}
	return o.Transaction, true
}

// HasTransaction returns a boolean if a field has been set.
func (o *Transaction) HasTransaction() bool {
	if o != nil && !IsNil(o.Transaction) {
		return true
	}

	return false
}

// SetTransaction gets a reference to the given map[string]Tx and assigns it to the Transaction field.
func (o *Transaction) SetTransaction(v map[string]Tx) {
	o.Transaction = &v
}

// GetUserOps returns the UserOps field value if set, zero value otherwise.
func (o *Transaction) GetUserOps() []TransactionRequest {
	if o == nil || IsNil(o.UserOps) {
		var ret []TransactionRequest
		return ret
	}
	return o.UserOps
}

// GetUserOpsOk returns a tuple with the UserOps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetUserOpsOk() ([]TransactionRequest, bool) {
	if o == nil || IsNil(o.UserOps) {
		return nil, false
	}
	return o.UserOps, true
}

// HasUserOps returns a boolean if a field has been set.
func (o *Transaction) HasUserOps() bool {
	if o != nil && !IsNil(o.UserOps) {
		return true
	}

	return false
}

// SetUserOps gets a reference to the given []TransactionRequest and assigns it to the UserOps field.
func (o *Transaction) SetUserOps(v []TransactionRequest) {
	o.UserOps = v
}

// GetUseropTransaction returns the UseropTransaction field value if set, zero value otherwise.
func (o *Transaction) GetUseropTransaction() string {
	if o == nil || IsNil(o.UseropTransaction) {
		var ret string
		return ret
	}
	return *o.UseropTransaction
}

// GetUseropTransactionOk returns a tuple with the UseropTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetUseropTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.UseropTransaction) {
		return nil, false
	}
	return o.UseropTransaction, true
}

// HasUseropTransaction returns a boolean if a field has been set.
func (o *Transaction) HasUseropTransaction() bool {
	if o != nil && !IsNil(o.UseropTransaction) {
		return true
	}

	return false
}

// SetUseropTransaction gets a reference to the given string and assigns it to the UseropTransaction field.
func (o *Transaction) SetUseropTransaction(v string) {
	o.UseropTransaction = &v
}

func (o Transaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MoonScanUrl) {
		toSerialize["moon_scan_url"] = o.MoonScanUrl
	}
	toSerialize["transaction_hash"] = o.TransactionHash
	toSerialize["signed_transaction"] = o.SignedTransaction
	if !IsNil(o.SignedMessage) {
		toSerialize["signed_message"] = o.SignedMessage
	}
	if !IsNil(o.RawTransaction) {
		toSerialize["raw_transaction"] = o.RawTransaction
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.Transaction) {
		toSerialize["transaction"] = o.Transaction
	}
	if !IsNil(o.UserOps) {
		toSerialize["userOps"] = o.UserOps
	}
	if !IsNil(o.UseropTransaction) {
		toSerialize["userop_transaction"] = o.UseropTransaction
	}
	return toSerialize, nil
}

func (o *Transaction) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction_hash",
		"signed_transaction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransaction := _Transaction{}

	err = json.Unmarshal(bytes, &varTransaction)

	if err != nil {
		return err
	}

	*o = Transaction(varTransaction)

	return err
}

type NullableTransaction struct {
	value *Transaction
	isSet bool
}

func (v NullableTransaction) Get() *Transaction {
	return v.value
}

func (v *NullableTransaction) Set(val *Transaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransaction(val *Transaction) *NullableTransaction {
	return &NullableTransaction{value: val, isSet: true}
}

func (v NullableTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


