/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moonsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AaveReservesData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AaveReservesData{}

// AaveReservesData struct for AaveReservesData
type AaveReservesData struct {
	CurrentAtokenBalance string `json:"current_atoken_balance"`
	CurrentBorrowBalance string `json:"current_borrow_balance"`
	PrincipalBorrowBalance string `json:"principal_borrow_balance"`
	BorrowRateMode string `json:"borrow_rate_mode"`
	BorrowRate string `json:"borrow_rate"`
	LiquidityRate string `json:"liquidity_rate"`
	OriginationFee string `json:"origination_fee"`
	VariableBorrowIndex string `json:"variable_borrow_index"`
	LastUpdateTimestamp string `json:"last_update_timestamp"`
	UsageAsCollateralEnabled string `json:"usage_as_collateral_enabled"`
}

type _AaveReservesData AaveReservesData

// NewAaveReservesData instantiates a new AaveReservesData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAaveReservesData(currentAtokenBalance string, currentBorrowBalance string, principalBorrowBalance string, borrowRateMode string, borrowRate string, liquidityRate string, originationFee string, variableBorrowIndex string, lastUpdateTimestamp string, usageAsCollateralEnabled string) *AaveReservesData {
	this := AaveReservesData{}
	this.CurrentAtokenBalance = currentAtokenBalance
	this.CurrentBorrowBalance = currentBorrowBalance
	this.PrincipalBorrowBalance = principalBorrowBalance
	this.BorrowRateMode = borrowRateMode
	this.BorrowRate = borrowRate
	this.LiquidityRate = liquidityRate
	this.OriginationFee = originationFee
	this.VariableBorrowIndex = variableBorrowIndex
	this.LastUpdateTimestamp = lastUpdateTimestamp
	this.UsageAsCollateralEnabled = usageAsCollateralEnabled
	return &this
}

// NewAaveReservesDataWithDefaults instantiates a new AaveReservesData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAaveReservesDataWithDefaults() *AaveReservesData {
	this := AaveReservesData{}
	return &this
}

// GetCurrentAtokenBalance returns the CurrentAtokenBalance field value
func (o *AaveReservesData) GetCurrentAtokenBalance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrentAtokenBalance
}

// GetCurrentAtokenBalanceOk returns a tuple with the CurrentAtokenBalance field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetCurrentAtokenBalanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentAtokenBalance, true
}

// SetCurrentAtokenBalance sets field value
func (o *AaveReservesData) SetCurrentAtokenBalance(v string) {
	o.CurrentAtokenBalance = v
}

// GetCurrentBorrowBalance returns the CurrentBorrowBalance field value
func (o *AaveReservesData) GetCurrentBorrowBalance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrentBorrowBalance
}

// GetCurrentBorrowBalanceOk returns a tuple with the CurrentBorrowBalance field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetCurrentBorrowBalanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentBorrowBalance, true
}

// SetCurrentBorrowBalance sets field value
func (o *AaveReservesData) SetCurrentBorrowBalance(v string) {
	o.CurrentBorrowBalance = v
}

// GetPrincipalBorrowBalance returns the PrincipalBorrowBalance field value
func (o *AaveReservesData) GetPrincipalBorrowBalance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalBorrowBalance
}

// GetPrincipalBorrowBalanceOk returns a tuple with the PrincipalBorrowBalance field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetPrincipalBorrowBalanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalBorrowBalance, true
}

// SetPrincipalBorrowBalance sets field value
func (o *AaveReservesData) SetPrincipalBorrowBalance(v string) {
	o.PrincipalBorrowBalance = v
}

// GetBorrowRateMode returns the BorrowRateMode field value
func (o *AaveReservesData) GetBorrowRateMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BorrowRateMode
}

// GetBorrowRateModeOk returns a tuple with the BorrowRateMode field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetBorrowRateModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BorrowRateMode, true
}

// SetBorrowRateMode sets field value
func (o *AaveReservesData) SetBorrowRateMode(v string) {
	o.BorrowRateMode = v
}

// GetBorrowRate returns the BorrowRate field value
func (o *AaveReservesData) GetBorrowRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BorrowRate
}

// GetBorrowRateOk returns a tuple with the BorrowRate field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetBorrowRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BorrowRate, true
}

// SetBorrowRate sets field value
func (o *AaveReservesData) SetBorrowRate(v string) {
	o.BorrowRate = v
}

// GetLiquidityRate returns the LiquidityRate field value
func (o *AaveReservesData) GetLiquidityRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LiquidityRate
}

// GetLiquidityRateOk returns a tuple with the LiquidityRate field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetLiquidityRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiquidityRate, true
}

// SetLiquidityRate sets field value
func (o *AaveReservesData) SetLiquidityRate(v string) {
	o.LiquidityRate = v
}

// GetOriginationFee returns the OriginationFee field value
func (o *AaveReservesData) GetOriginationFee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OriginationFee
}

// GetOriginationFeeOk returns a tuple with the OriginationFee field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetOriginationFeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginationFee, true
}

// SetOriginationFee sets field value
func (o *AaveReservesData) SetOriginationFee(v string) {
	o.OriginationFee = v
}

// GetVariableBorrowIndex returns the VariableBorrowIndex field value
func (o *AaveReservesData) GetVariableBorrowIndex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VariableBorrowIndex
}

// GetVariableBorrowIndexOk returns a tuple with the VariableBorrowIndex field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetVariableBorrowIndexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VariableBorrowIndex, true
}

// SetVariableBorrowIndex sets field value
func (o *AaveReservesData) SetVariableBorrowIndex(v string) {
	o.VariableBorrowIndex = v
}

// GetLastUpdateTimestamp returns the LastUpdateTimestamp field value
func (o *AaveReservesData) GetLastUpdateTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastUpdateTimestamp
}

// GetLastUpdateTimestampOk returns a tuple with the LastUpdateTimestamp field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetLastUpdateTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdateTimestamp, true
}

// SetLastUpdateTimestamp sets field value
func (o *AaveReservesData) SetLastUpdateTimestamp(v string) {
	o.LastUpdateTimestamp = v
}

// GetUsageAsCollateralEnabled returns the UsageAsCollateralEnabled field value
func (o *AaveReservesData) GetUsageAsCollateralEnabled() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UsageAsCollateralEnabled
}

// GetUsageAsCollateralEnabledOk returns a tuple with the UsageAsCollateralEnabled field value
// and a boolean to check if the value has been set.
func (o *AaveReservesData) GetUsageAsCollateralEnabledOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsageAsCollateralEnabled, true
}

// SetUsageAsCollateralEnabled sets field value
func (o *AaveReservesData) SetUsageAsCollateralEnabled(v string) {
	o.UsageAsCollateralEnabled = v
}

func (o AaveReservesData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AaveReservesData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current_atoken_balance"] = o.CurrentAtokenBalance
	toSerialize["current_borrow_balance"] = o.CurrentBorrowBalance
	toSerialize["principal_borrow_balance"] = o.PrincipalBorrowBalance
	toSerialize["borrow_rate_mode"] = o.BorrowRateMode
	toSerialize["borrow_rate"] = o.BorrowRate
	toSerialize["liquidity_rate"] = o.LiquidityRate
	toSerialize["origination_fee"] = o.OriginationFee
	toSerialize["variable_borrow_index"] = o.VariableBorrowIndex
	toSerialize["last_update_timestamp"] = o.LastUpdateTimestamp
	toSerialize["usage_as_collateral_enabled"] = o.UsageAsCollateralEnabled
	return toSerialize, nil
}

func (o *AaveReservesData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current_atoken_balance",
		"current_borrow_balance",
		"principal_borrow_balance",
		"borrow_rate_mode",
		"borrow_rate",
		"liquidity_rate",
		"origination_fee",
		"variable_borrow_index",
		"last_update_timestamp",
		"usage_as_collateral_enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAaveReservesData := _AaveReservesData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAaveReservesData)

	if err != nil {
		return err
	}

	*o = AaveReservesData(varAaveReservesData)

	return err
}

type NullableAaveReservesData struct {
	value *AaveReservesData
	isSet bool
}

func (v NullableAaveReservesData) Get() *AaveReservesData {
	return v.value
}

func (v *NullableAaveReservesData) Set(val *AaveReservesData) {
	v.value = val
	v.isSet = true
}

func (v NullableAaveReservesData) IsSet() bool {
	return v.isSet
}

func (v *NullableAaveReservesData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAaveReservesData(val *AaveReservesData) *NullableAaveReservesData {
	return &NullableAaveReservesData{value: val, isSet: true}
}

func (v NullableAaveReservesData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAaveReservesData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


