/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moonsdk

import (
	"encoding/json"
)

// checks if the LitecoinInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LitecoinInput{}

// LitecoinInput struct for LitecoinInput
type LitecoinInput struct {
	Network *string `json:"network,omitempty"`
	PrivateKey *string `json:"private_key,omitempty"`
}

// NewLitecoinInput instantiates a new LitecoinInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLitecoinInput() *LitecoinInput {
	this := LitecoinInput{}
	return &this
}

// NewLitecoinInputWithDefaults instantiates a new LitecoinInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLitecoinInputWithDefaults() *LitecoinInput {
	this := LitecoinInput{}
	return &this
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *LitecoinInput) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LitecoinInput) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *LitecoinInput) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *LitecoinInput) SetNetwork(v string) {
	o.Network = &v
}

// GetPrivateKey returns the PrivateKey field value if set, zero value otherwise.
func (o *LitecoinInput) GetPrivateKey() string {
	if o == nil || IsNil(o.PrivateKey) {
		var ret string
		return ret
	}
	return *o.PrivateKey
}

// GetPrivateKeyOk returns a tuple with the PrivateKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LitecoinInput) GetPrivateKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateKey) {
		return nil, false
	}
	return o.PrivateKey, true
}

// HasPrivateKey returns a boolean if a field has been set.
func (o *LitecoinInput) HasPrivateKey() bool {
	if o != nil && !IsNil(o.PrivateKey) {
		return true
	}

	return false
}

// SetPrivateKey gets a reference to the given string and assigns it to the PrivateKey field.
func (o *LitecoinInput) SetPrivateKey(v string) {
	o.PrivateKey = &v
}

func (o LitecoinInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LitecoinInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.PrivateKey) {
		toSerialize["private_key"] = o.PrivateKey
	}
	return toSerialize, nil
}

type NullableLitecoinInput struct {
	value *LitecoinInput
	isSet bool
}

func (v NullableLitecoinInput) Get() *LitecoinInput {
	return v.value
}

func (v *NullableLitecoinInput) Set(val *LitecoinInput) {
	v.value = val
	v.isSet = true
}

func (v NullableLitecoinInput) IsSet() bool {
	return v.isSet
}

func (v *NullableLitecoinInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLitecoinInput(val *LitecoinInput) *NullableLitecoinInput {
	return &NullableLitecoinInput{value: val, isSet: true}
}

func (v NullableLitecoinInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLitecoinInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


