/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moonsdk

import (
	"encoding/json"
)

// checks if the SolanaInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SolanaInput{}

// SolanaInput struct for SolanaInput
type SolanaInput struct {
	Network *string `json:"network,omitempty"`
	PrivateKey *string `json:"private_key,omitempty"`
}

// NewSolanaInput instantiates a new SolanaInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSolanaInput() *SolanaInput {
	this := SolanaInput{}
	return &this
}

// NewSolanaInputWithDefaults instantiates a new SolanaInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSolanaInputWithDefaults() *SolanaInput {
	this := SolanaInput{}
	return &this
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *SolanaInput) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolanaInput) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *SolanaInput) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *SolanaInput) SetNetwork(v string) {
	o.Network = &v
}

// GetPrivateKey returns the PrivateKey field value if set, zero value otherwise.
func (o *SolanaInput) GetPrivateKey() string {
	if o == nil || IsNil(o.PrivateKey) {
		var ret string
		return ret
	}
	return *o.PrivateKey
}

// GetPrivateKeyOk returns a tuple with the PrivateKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolanaInput) GetPrivateKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateKey) {
		return nil, false
	}
	return o.PrivateKey, true
}

// HasPrivateKey returns a boolean if a field has been set.
func (o *SolanaInput) HasPrivateKey() bool {
	if o != nil && !IsNil(o.PrivateKey) {
		return true
	}

	return false
}

// SetPrivateKey gets a reference to the given string and assigns it to the PrivateKey field.
func (o *SolanaInput) SetPrivateKey(v string) {
	o.PrivateKey = &v
}

func (o SolanaInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SolanaInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.PrivateKey) {
		toSerialize["private_key"] = o.PrivateKey
	}
	return toSerialize, nil
}

type NullableSolanaInput struct {
	value *SolanaInput
	isSet bool
}

func (v NullableSolanaInput) Get() *SolanaInput {
	return v.value
}

func (v *NullableSolanaInput) Set(val *SolanaInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSolanaInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSolanaInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSolanaInput(val *SolanaInput) *NullableSolanaInput {
	return &NullableSolanaInput{value: val, isSet: true}
}

func (v NullableSolanaInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSolanaInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


