/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moonsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InternalTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalTransaction{}

// InternalTransaction struct for InternalTransaction
type InternalTransaction struct {
	From NullableString `json:"from"`
	To NullableString `json:"to"`
	Value NullableString `json:"value"`
	TransactionHash string `json:"transactionHash"`
	Gas NullableString `json:"gas"`
}

type _InternalTransaction InternalTransaction

// NewInternalTransaction instantiates a new InternalTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalTransaction(from NullableString, to NullableString, value NullableString, transactionHash string, gas NullableString) *InternalTransaction {
	this := InternalTransaction{}
	this.From = from
	this.To = to
	this.Value = value
	this.TransactionHash = transactionHash
	this.Gas = gas
	return &this
}

// NewInternalTransactionWithDefaults instantiates a new InternalTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalTransactionWithDefaults() *InternalTransaction {
	this := InternalTransaction{}
	return &this
}

// GetFrom returns the From field value
// If the value is explicit nil, the zero value for string will be returned
func (o *InternalTransaction) GetFrom() string {
	if o == nil || o.From.Get() == nil {
		var ret string
		return ret
	}

	return *o.From.Get()
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalTransaction) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.From.Get(), o.From.IsSet()
}

// SetFrom sets field value
func (o *InternalTransaction) SetFrom(v string) {
	o.From.Set(&v)
}

// GetTo returns the To field value
// If the value is explicit nil, the zero value for string will be returned
func (o *InternalTransaction) GetTo() string {
	if o == nil || o.To.Get() == nil {
		var ret string
		return ret
	}

	return *o.To.Get()
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalTransaction) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.To.Get(), o.To.IsSet()
}

// SetTo sets field value
func (o *InternalTransaction) SetTo(v string) {
	o.To.Set(&v)
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for string will be returned
func (o *InternalTransaction) GetValue() string {
	if o == nil || o.Value.Get() == nil {
		var ret string
		return ret
	}

	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalTransaction) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// SetValue sets field value
func (o *InternalTransaction) SetValue(v string) {
	o.Value.Set(&v)
}

// GetTransactionHash returns the TransactionHash field value
func (o *InternalTransaction) GetTransactionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value
// and a boolean to check if the value has been set.
func (o *InternalTransaction) GetTransactionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionHash, true
}

// SetTransactionHash sets field value
func (o *InternalTransaction) SetTransactionHash(v string) {
	o.TransactionHash = v
}

// GetGas returns the Gas field value
// If the value is explicit nil, the zero value for string will be returned
func (o *InternalTransaction) GetGas() string {
	if o == nil || o.Gas.Get() == nil {
		var ret string
		return ret
	}

	return *o.Gas.Get()
}

// GetGasOk returns a tuple with the Gas field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InternalTransaction) GetGasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gas.Get(), o.Gas.IsSet()
}

// SetGas sets field value
func (o *InternalTransaction) SetGas(v string) {
	o.Gas.Set(&v)
}

func (o InternalTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From.Get()
	toSerialize["to"] = o.To.Get()
	toSerialize["value"] = o.Value.Get()
	toSerialize["transactionHash"] = o.TransactionHash
	toSerialize["gas"] = o.Gas.Get()
	return toSerialize, nil
}

func (o *InternalTransaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
		"value",
		"transactionHash",
		"gas",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInternalTransaction := _InternalTransaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInternalTransaction)

	if err != nil {
		return err
	}

	*o = InternalTransaction(varInternalTransaction)

	return err
}

type NullableInternalTransaction struct {
	value *InternalTransaction
	isSet bool
}

func (v NullableInternalTransaction) Get() *InternalTransaction {
	return v.value
}

func (v *NullableInternalTransaction) Set(val *InternalTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalTransaction(val *InternalTransaction) *NullableInternalTransaction {
	return &NullableInternalTransaction{value: val, isSet: true}
}

func (v NullableInternalTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


