/*
moon-vault-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the Erc1155Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Erc1155Response{}

// Erc1155Response struct for Erc1155Response
type Erc1155Response struct {
	MoonScanUrl *string `json:"moon_scan_url,omitempty"`
	TransactionHash string `json:"transaction_hash"`
	SignedTransaction string `json:"signed_transaction"`
	SignedMessage *string `json:"signed_message,omitempty"`
	RawTransaction *string `json:"raw_transaction,omitempty"`
	Signature *string `json:"signature,omitempty"`
	Transaction *map[string]Tx `json:"transaction,omitempty"`
	UserOps []TransactionRequest `json:"userOps,omitempty"`
	UseropTransaction *string `json:"userop_transaction,omitempty"`
	BalanceOf *string `json:"balance_of,omitempty"`
	BalanceOfBatch *string `json:"balance_of_batch,omitempty"`
}

type _Erc1155Response Erc1155Response

// NewErc1155Response instantiates a new Erc1155Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErc1155Response(transactionHash string, signedTransaction string) *Erc1155Response {
	this := Erc1155Response{}
	this.TransactionHash = transactionHash
	this.SignedTransaction = signedTransaction
	return &this
}

// NewErc1155ResponseWithDefaults instantiates a new Erc1155Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErc1155ResponseWithDefaults() *Erc1155Response {
	this := Erc1155Response{}
	return &this
}

// GetMoonScanUrl returns the MoonScanUrl field value if set, zero value otherwise.
func (o *Erc1155Response) GetMoonScanUrl() string {
	if o == nil || IsNil(o.MoonScanUrl) {
		var ret string
		return ret
	}
	return *o.MoonScanUrl
}

// GetMoonScanUrlOk returns a tuple with the MoonScanUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetMoonScanUrlOk() (*string, bool) {
	if o == nil || IsNil(o.MoonScanUrl) {
		return nil, false
	}
	return o.MoonScanUrl, true
}

// HasMoonScanUrl returns a boolean if a field has been set.
func (o *Erc1155Response) HasMoonScanUrl() bool {
	if o != nil && !IsNil(o.MoonScanUrl) {
		return true
	}

	return false
}

// SetMoonScanUrl gets a reference to the given string and assigns it to the MoonScanUrl field.
func (o *Erc1155Response) SetMoonScanUrl(v string) {
	o.MoonScanUrl = &v
}

// GetTransactionHash returns the TransactionHash field value
func (o *Erc1155Response) GetTransactionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetTransactionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionHash, true
}

// SetTransactionHash sets field value
func (o *Erc1155Response) SetTransactionHash(v string) {
	o.TransactionHash = v
}

// GetSignedTransaction returns the SignedTransaction field value
func (o *Erc1155Response) GetSignedTransaction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignedTransaction
}

// GetSignedTransactionOk returns a tuple with the SignedTransaction field value
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetSignedTransactionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignedTransaction, true
}

// SetSignedTransaction sets field value
func (o *Erc1155Response) SetSignedTransaction(v string) {
	o.SignedTransaction = v
}

// GetSignedMessage returns the SignedMessage field value if set, zero value otherwise.
func (o *Erc1155Response) GetSignedMessage() string {
	if o == nil || IsNil(o.SignedMessage) {
		var ret string
		return ret
	}
	return *o.SignedMessage
}

// GetSignedMessageOk returns a tuple with the SignedMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetSignedMessageOk() (*string, bool) {
	if o == nil || IsNil(o.SignedMessage) {
		return nil, false
	}
	return o.SignedMessage, true
}

// HasSignedMessage returns a boolean if a field has been set.
func (o *Erc1155Response) HasSignedMessage() bool {
	if o != nil && !IsNil(o.SignedMessage) {
		return true
	}

	return false
}

// SetSignedMessage gets a reference to the given string and assigns it to the SignedMessage field.
func (o *Erc1155Response) SetSignedMessage(v string) {
	o.SignedMessage = &v
}

// GetRawTransaction returns the RawTransaction field value if set, zero value otherwise.
func (o *Erc1155Response) GetRawTransaction() string {
	if o == nil || IsNil(o.RawTransaction) {
		var ret string
		return ret
	}
	return *o.RawTransaction
}

// GetRawTransactionOk returns a tuple with the RawTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetRawTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.RawTransaction) {
		return nil, false
	}
	return o.RawTransaction, true
}

// HasRawTransaction returns a boolean if a field has been set.
func (o *Erc1155Response) HasRawTransaction() bool {
	if o != nil && !IsNil(o.RawTransaction) {
		return true
	}

	return false
}

// SetRawTransaction gets a reference to the given string and assigns it to the RawTransaction field.
func (o *Erc1155Response) SetRawTransaction(v string) {
	o.RawTransaction = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *Erc1155Response) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *Erc1155Response) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *Erc1155Response) SetSignature(v string) {
	o.Signature = &v
}

// GetTransaction returns the Transaction field value if set, zero value otherwise.
func (o *Erc1155Response) GetTransaction() map[string]Tx {
	if o == nil || IsNil(o.Transaction) {
		var ret map[string]Tx
		return ret
	}
	return *o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetTransactionOk() (*map[string]Tx, bool) {
	if o == nil || IsNil(o.Transaction) {
		return nil, false
	}
	return o.Transaction, true
}

// HasTransaction returns a boolean if a field has been set.
func (o *Erc1155Response) HasTransaction() bool {
	if o != nil && !IsNil(o.Transaction) {
		return true
	}

	return false
}

// SetTransaction gets a reference to the given map[string]Tx and assigns it to the Transaction field.
func (o *Erc1155Response) SetTransaction(v map[string]Tx) {
	o.Transaction = &v
}

// GetUserOps returns the UserOps field value if set, zero value otherwise.
func (o *Erc1155Response) GetUserOps() []TransactionRequest {
	if o == nil || IsNil(o.UserOps) {
		var ret []TransactionRequest
		return ret
	}
	return o.UserOps
}

// GetUserOpsOk returns a tuple with the UserOps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetUserOpsOk() ([]TransactionRequest, bool) {
	if o == nil || IsNil(o.UserOps) {
		return nil, false
	}
	return o.UserOps, true
}

// HasUserOps returns a boolean if a field has been set.
func (o *Erc1155Response) HasUserOps() bool {
	if o != nil && !IsNil(o.UserOps) {
		return true
	}

	return false
}

// SetUserOps gets a reference to the given []TransactionRequest and assigns it to the UserOps field.
func (o *Erc1155Response) SetUserOps(v []TransactionRequest) {
	o.UserOps = v
}

// GetUseropTransaction returns the UseropTransaction field value if set, zero value otherwise.
func (o *Erc1155Response) GetUseropTransaction() string {
	if o == nil || IsNil(o.UseropTransaction) {
		var ret string
		return ret
	}
	return *o.UseropTransaction
}

// GetUseropTransactionOk returns a tuple with the UseropTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetUseropTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.UseropTransaction) {
		return nil, false
	}
	return o.UseropTransaction, true
}

// HasUseropTransaction returns a boolean if a field has been set.
func (o *Erc1155Response) HasUseropTransaction() bool {
	if o != nil && !IsNil(o.UseropTransaction) {
		return true
	}

	return false
}

// SetUseropTransaction gets a reference to the given string and assigns it to the UseropTransaction field.
func (o *Erc1155Response) SetUseropTransaction(v string) {
	o.UseropTransaction = &v
}

// GetBalanceOf returns the BalanceOf field value if set, zero value otherwise.
func (o *Erc1155Response) GetBalanceOf() string {
	if o == nil || IsNil(o.BalanceOf) {
		var ret string
		return ret
	}
	return *o.BalanceOf
}

// GetBalanceOfOk returns a tuple with the BalanceOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetBalanceOfOk() (*string, bool) {
	if o == nil || IsNil(o.BalanceOf) {
		return nil, false
	}
	return o.BalanceOf, true
}

// HasBalanceOf returns a boolean if a field has been set.
func (o *Erc1155Response) HasBalanceOf() bool {
	if o != nil && !IsNil(o.BalanceOf) {
		return true
	}

	return false
}

// SetBalanceOf gets a reference to the given string and assigns it to the BalanceOf field.
func (o *Erc1155Response) SetBalanceOf(v string) {
	o.BalanceOf = &v
}

// GetBalanceOfBatch returns the BalanceOfBatch field value if set, zero value otherwise.
func (o *Erc1155Response) GetBalanceOfBatch() string {
	if o == nil || IsNil(o.BalanceOfBatch) {
		var ret string
		return ret
	}
	return *o.BalanceOfBatch
}

// GetBalanceOfBatchOk returns a tuple with the BalanceOfBatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Erc1155Response) GetBalanceOfBatchOk() (*string, bool) {
	if o == nil || IsNil(o.BalanceOfBatch) {
		return nil, false
	}
	return o.BalanceOfBatch, true
}

// HasBalanceOfBatch returns a boolean if a field has been set.
func (o *Erc1155Response) HasBalanceOfBatch() bool {
	if o != nil && !IsNil(o.BalanceOfBatch) {
		return true
	}

	return false
}

// SetBalanceOfBatch gets a reference to the given string and assigns it to the BalanceOfBatch field.
func (o *Erc1155Response) SetBalanceOfBatch(v string) {
	o.BalanceOfBatch = &v
}

func (o Erc1155Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Erc1155Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MoonScanUrl) {
		toSerialize["moon_scan_url"] = o.MoonScanUrl
	}
	toSerialize["transaction_hash"] = o.TransactionHash
	toSerialize["signed_transaction"] = o.SignedTransaction
	if !IsNil(o.SignedMessage) {
		toSerialize["signed_message"] = o.SignedMessage
	}
	if !IsNil(o.RawTransaction) {
		toSerialize["raw_transaction"] = o.RawTransaction
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.Transaction) {
		toSerialize["transaction"] = o.Transaction
	}
	if !IsNil(o.UserOps) {
		toSerialize["userOps"] = o.UserOps
	}
	if !IsNil(o.UseropTransaction) {
		toSerialize["userop_transaction"] = o.UseropTransaction
	}
	if !IsNil(o.BalanceOf) {
		toSerialize["balance_of"] = o.BalanceOf
	}
	if !IsNil(o.BalanceOfBatch) {
		toSerialize["balance_of_batch"] = o.BalanceOfBatch
	}
	return toSerialize, nil
}

func (o *Erc1155Response) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction_hash",
		"signed_transaction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErc1155Response := _Erc1155Response{}

	err = json.Unmarshal(bytes, &varErc1155Response)

	if err != nil {
		return err
	}

	*o = Erc1155Response(varErc1155Response)

	return err
}

type NullableErc1155Response struct {
	value *Erc1155Response
	isSet bool
}

func (v NullableErc1155Response) Get() *Erc1155Response {
	return v.value
}

func (v *NullableErc1155Response) Set(val *Erc1155Response) {
	v.value = val
	v.isSet = true
}

func (v NullableErc1155Response) IsSet() bool {
	return v.isSet
}

func (v *NullableErc1155Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErc1155Response(val *Erc1155Response) *NullableErc1155Response {
	return &NullableErc1155Response{value: val, isSet: true}
}

func (v NullableErc1155Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErc1155Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


